language: java

jdk:
  - wget -r --no-parent --reject "index.html*" https://download.java.net/java/GA/jdk21.0.2/f2283984656d49d69e91c558476027ac/13/GPL/openjdk-21.0.2_linux-x64_bin.tar.gz


install: mvn install -B sonar:sonar -Dsonar.login=${SONAR_TOKEN}

after_success: ./report.sh

after_failure: ./report.sh

notifications:
  email:
    recipients:
      - Juansaintaurautomation@gmail.com
      - Juansaintaurautomation@gmail.com
      - Juansaintaurautomation@gmail.com
      - Juansaintaurautomation@gmail.com
      - Juansaintaurautomation@gmail.com
      - Juansaintaurautomation@gmail.com
      - Juansaintaurautomation@gmail.com
      - Juansaintaurautomation@gmail.com
      - Juansaintaurautomation@gmail.com
      - Juansaintaurautomation@gmail.com
      - Juansaintaurautomation@gmail.com
      - Juansaintaurautomation@gmail.com
      - Juansaintaurautomation@gmail.com
      - Juansaintaurautomation@gmail.com
      - Juansaintaurautomation@gmail.com
      - Juansaintaurautomation@gmail.com
      - Juansaintaurautomation@gmail.com
      - Juansaintaurautomation@gmail.com
      - Juansaintaurautomation@gmail.com
    on_success: always
    on_failure: always
 
